# Generated by Django 4.2.6 on 2023-10-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_score_count_user_score_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="register_code",
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
