# Generated by Django 4.2.6 on 2023-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_register_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="score_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Score count"),
        ),
        migrations.AlterField(
            model_name="user",
            name="score_sum",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Score sum"),
        ),
    ]
